name: closet_organizer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI関連
  cupertino_icons: ^1.0.8

  # カメラ・画像関連
  camera: ^0.11.0
  image_picker: ^1.1.2
  image: ^4.2.0

  # 権限管理
  permission_handler: ^11.3.1

  # 状態管理
  provider: ^6.1.2

  # データ保存
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  path_provider: ^2.1.4
  path: ^1.9.0

  # API通信
  http: ^1.2.2
  dio: ^5.7.0

  # UI拡張
  flutter_slidable: ^3.1.1
  fl_chart: ^0.69.0

  # ユーティリティ
  uuid: ^4.5.1
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^19.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # アセット設定
  assets:
    - .env
    # 今後画像を追加する場合
    # - assets/images/
    # - assets/icons/

  # フォント設定（必要に応じて）
  # fonts:
  #   - family: NotoSansJP
  #     fonts:
  #       - asset: fonts/NotoSansJP-Regular.otf
  #       - asset: fonts/NotoSansJP-Bold.otf
  #         weight: 700